/**
 *
 *
 * Array que descompone las localizaciones de Chile
 * region  -> corresponde al nombre de las regiones
 * comunas -> corresponde a las comunas de las regiones
 */

export const regionCiudades = {
  "Arica y Parinacota": ["Arica", "Parinacota"],
  Tarapacá: ["Iquique", "Tamarugal"],
  Antofagasta: ["Antofagasta", "El Loa", "Tocopilla"],
  Atacama: ["Copiapó", "Chañaral", "Huasco"],
  Coquimbo: ["Elqui", "Choapa", "Limarí"],
  Valparaíso: [
    "Valparaíso",
    "Isla de Pascua",
    "Los Andes",
    "Petorca",
    "Quillota",
    "San Antonio",
    "San Felipe de Aconcagua",
    "Marga Marga",
  ],
  "Libertador General Bernardo O’Higgins": [
    "Cachapoal",
    "Cardenal Caro",
    "Colchagua",
  ],
  "Maule": ["Talca", "Cauquenes", "Curicó", "Linares"],
  "Ñuble": ["Diguillín", "Itata", "Punilla"],
  "Biobío": ["Concepción", "Arauco", "Biobío", "Ñuble"],
  "La Araucanía": ["Cautín", "Malleco"],
  "Los Ríos": ["Valdivia", "Ranco"],
  "Los Lagos": ["Llanquihue", "Chiloé", "Osorno", "Palena"],
  "Aysén del General Carlos Ibáñez del Campo": [
    "Aysén",
    "Capitán Prat",
    "Coyhaique",
    "General Carrera",
  ],
  "Magallanes y de la Antártica Chilena": [
    "Magallanes",
    "Antártica Chilena",
    "Tierra del Fuego",
    "Última Esperanza",
  ],
  "Metropolitana de Santiago": [
    "Santiago",
    "Cordillera",
    "Chacabuco",
    "Maipo",
    "Melipilla",
    "Talagante",
  ],
};

export const ciudadComunas = {
  Arica: ["Arica", "Camarones"],
  Parinacota: ["Putre", "General Lagos"],
  Iquique: ["Iquique", "Alto Hospicio"],
  Tamarugal: ["Camiña", "Colchane", "Huara", "Pica", "Pozo Almonte"],
  Antofagasta: ["Antofagasta", "Mejillones", "Sierra Gorda", "Taltal"],
  "El Loa": ["Calama", "Ollagüe", "San Pedro de Atacama"],
  Tocopilla: ["Tocopilla", "María Elena"],
  Copiapó: ["Copiapó", "Caldera", "Tierra Amarilla"],
  Chañaral: ["Chañaral", "Diego de Almagro"],
  Huasco: ["Vallenar", "Alto del Carmen", "Freirina", "Huasco"],
  Elqui: [
    "La Serena",
    "Coquimbo",
    "Andacollo",
    "La Higuera",
    "Paiguano",
    "Vicuña",
  ],
  Choapa: ["Illapel", "Canela", "Los Vilos", "Salamanca"],
  Limarí: ["Ovalle", "Combarbalá", "Monte Patria", "Punitaqui", "Río Hurtado"],
  Valparaíso: [
    "Valparaíso",
    "Casablanca",
    "Concón",
    "Juan Fernández",
    "Puchuncaví",
    "Quintero",
    "Viña del Mar",
  ],
  "Isla de Pascua": ["Isla de Pascua"],
  "Los Andes": ["Los Andes", "Calle Larga", "Rinconada", "San Esteban"],
  Petorca: ["La Ligua", "Cabildo", "Papudo", "Petorca", "Zapallar"],
  Quillota: ["Quillota", "Calera", "Hijuelas", "La Cruz", "Nogales"],
  "San Antonio": [
    "San Antonio",
    "Algarrobo",
    "Cartagena",
    "El Quisco",
    "El Tabo",
    "Santo Domingo",
  ],
  "San Felipe de Aconcagua": [
    "San Felipe",
    "Catemu",
    "Llaillay",
    "Panquehue",
    "Putaendo",
    "Santa María",
  ],
  "Marga Marga": ["Quilpué", "Limache", "Olmué", "Villa Alemana"],
  Cachapoal: [
    "Rancagua",
    "Codegua",
    "Coinco",
    "Coltauco",
    "Doñihue",
    "Graneros",
    "Las Cabras",
    "Machalí",
    "Malloa",
    "Mostazal",
    "Olivar",
    "Peumo",
    "Pichidegua",
    "Quinta de Tilcoco",
    "Rengo",
    "Requínoa",
    "San Vicente",
  ],
  "Cardenal Caro": [
    "Pichilemu",
    "La Estrella",
    "Litueche",
    "Marchihue",
    "Navidad",
    "Paredones",
  ],
  Colchagua: ["San Fernando", "Chépica", "Chimbarongo", "Lolol", "Nancagua", "Palmilla", "Peralillo", "Placilla", "Pumanque", "Santa Cruz"],	
  Talca: ["Talca", "Constitución", "Curepto", "Empedrado", "Maule", "Pelarco", "Pencahue", "Río Claro", "San Clemente", "San Rafael"],
  Cauquenes: ["Cauquenes", "Chanco", "Pelluhue"],
  Curicó: ["Curicó", "Hualañé", "Licantén", "Molina", "Rauco", "Romeral", "Sagrada Familia", "Teno", "Vichuquén"],
  Linares: ["Linares", "Colbún", "Longaví", "Parral", "Retiro", "San Javier", "Villa Alegre", "Yerbas Buenas"],
  Diguillín: ["Bulnes", "Chillán Viejo", "Chillán", "El Carmen", "Pemuco", "Pinto", "Quillón", "San Ignacio", "Yungay"],
  Itata: ["Cobquecura", "Coelemu", "Ninhue", "Portezuelo", "Quirihue", "Ránquil", "Treguaco"],
  Punilla: ["Coihueco", "Ñiquén", "San Carlos", "San Fabián", "San Nicolás"],
  Concepción: ["Concepción", "Coronel", "Chiguayante", "Florida", "Hualqui", "Lota", "Penco", "San Pedro de la Paz", "Santa Juana", "Talcahuano", "Tomé", "Hualpén"],
  Arauco: ["Lebu", "Arauco", "Cañete", "Contulmo", "Curanilahue", "Los Álamos", "Tirúa"],
  Biobío: ["Los Ángeles", "Antuco", "Cabrero", "Laja", "Mulchén", "Nacimiento", "Negrete", "Quilaco", "Quilleco", "San Rosendo", "Santa Bárbara", "Tucapel", "Yumbel", "Alto Biobío"],
  Cautín: ["Temuco", "Carahue", "Cunco", "Curarrehue", "Freire", "Galvarino", "Gorbea", "Lautaro", "Loncoche", "Melipeuco", "Nueva Imperial", "Padre las Casas", "Perquenco", "Pitrufquén", "Pucón", "Saavedra", "Teodoro Schmidt", "Toltén", "Vilcún", "Villarrica", "Cholchol"],
  Malleco: ["Angol", "Collipulli", "Curacautín", "Ercilla", "Lonquimay", "Los Sauces", "Lumaco", "Purén", "Renaico", "Traiguén", "Victoria"],
  Valdivia: ["Valdivia", "Corral", "Lanco", "Los Lagos", "Máfil", "Mariquina", "Paillaco", "Panguipulli"],
  Ranco: ["La Unión", "Futrono", "Lago Ranco", "Río Bueno"],
  Llanquihue: ["Puerto Montt", "Calbuco", "Cochamó", "Fresia", "Frutillar", "Los Muermos", "Llanquihue", "Maullín", "Puerto Varas"],
  Chiloé: [
    "Castro",	
    "Ancud",
    "Chonchi",
    "Curaco de Vélez",
    "Dalcahue",
    "Puqueldón",
    "Queilén",
    "Quellón",
    "Quemchi",
    "Quinchao"
  ],
  Osorno: [
    "Osorno",
    "Puerto Octay",
    "Purranque",
    "Puyehue",
    "Río Negro",
    "San Pablo",
    "San Juan"
  ],
  Palena: [
    'Chaitén',
    'Futaleufú',
    'Hualaihué',
    'Palena'  
  ],
  Aysén: [
    'Aysén',
    'Cisnes',
    'Guaitecas'
  ],
  "Capitán Prat": [
    'Cochrane',
    "O'Higgins",
    'Tortel'
  ],
  Coyhaique: [
    'Coyhaique',
    'Lago Verde'
  ],
  "General Carrera": [
    'Chile Chico',
    'Río Ibáñez'
  ],
  Magallanes: [
    'Laguna Blanca',
    'Punta Arenas',
    'Río Verde',
    'San Gregorio'
  ],
  "Antártica Chilena": [],
  "Tierra del Fuego": [
    'Porvenir',
    'Primavera',
    'Timaukel'
  ],
  "Última Esperanza": [
    "Natales",
    "Torres del Paine"
  ],
  Santiago: [
    'Cerrillos',
    'Cerro Navia',
    'Conchalí',
    'El Bosque',
    'Estación Central',
    'Huechuraba',
    'Independencia',
    'La Cisterna',
    'La Granja',
    'La Florida',
    'La Pintana',
    'La Reina',
    'Las Condes',
    'Lo Barnechea',
    'Lo Espejo',
    'Lo Prado',
    'Macul',
    'Maipú',
    'Ñuñoa',
    'Pedro Aguirre Cerda',
    'Peñalolén',
    'Providencia',
    'Pudahuel',
    'Quilicura',
    'Quinta Normal',
    'Recoleta',
    'Renca',
    'San Miguel',
    'San Joaquín',
    "San Ramón",
    "Santiago",
    "Vitacura",
  ],
  Cordillera: [
    "Pirque",
    "Puente Alto",
    "San José de Maipo"
  ],
  Chacabuco: [
    "Colina",
    "Lampa",
    "Tiltil"
  ],
  Maipo: [
    "Buin",
    "Calera de Tango",
    "Paine",
    "San Bernardo"
  ],
  Melipilla: [
    "Alhué",
    "Curacaví",
    "María Pinto",
    "Melipilla",
    "San Pedro"
  ],
  Talagante: [
    "El Monte",
    "Isla de Maipo",
    "Padre Hurtado",
    "Peñaflor",
    "Talagante"
  ],
};

export const locationsChile = {
  "Arica y Parinacota": ["Arica", "Camarones", "Putre", "General Lagos"],
  Tarapacá: [
    "Iquique",
    "Alto Hospicio",
    "Pozo Almonte",
    "Camiña",
    "Colchane",
    "Huara",
    "Pica",
  ],
  Antofagasta: [
    "Antofagasta",
    "Mejillones",
    "Sierra Gorda",
    "Taltal",
    "Calama",
    "Ollagüe",
    "San Pedro de Atacama",
    "Tocopilla",
    "María Elena",
  ],
  Atacama: [
    "Copiapó",
    "Caldera",
    "Tierra Amarilla",
    "Chañaral",
    "Diego de Almagro",
    "Vallenar",
    "Alto del Carmen",
    "Freirina",
    "Huasco",
  ],
  Coquimbo: [
    "La Serena",
    "Coquimbo",
    "Andacollo",
    "La Higuera",
    "Paiguano",
    "Vicuña",
    "Illapel",
    "Canela",
    "Los Vilos",
    "Salamanca",
    "Ovalle",
    "Combarbalá",
    "Monte Patria",
    "Punitaqui",
    "Río Hurtado",
  ],
  Valparaíso: [
    "Valparaíso",
    "Casablanca",
    "Concón",
    "Juan Fernández",
    "Puchuncaví",
    "Quintero",
    "Viña del Mar",
    "Isla de Pascua",
    "Los Andes",
    "Calle Larga",
    "Rinconada",
    "San Esteban",
    "La Ligua",
    "Cabildo",
    "Papudo",
    "Petorca",
    "Zapallar",
    "Quillota",
    "Calera",
    "Hijuelas",
    "La Cruz",
    "Nogales",
    "San Antonio",
    "Algarrobo",
    "Cartagena",
    "El Quisco",
    "El Tabo",
    "Santo Domingo",
    "San Felipe",
    "Catemu",
    "Llaillay",
    "Panquehue",
    "Putaendo",
    "Santa María",
    "Quilpué",
    "Limache",
    "Olmué",
    "Villa Alemana",
  ],
  "Región del Libertador Gral. Bernardo O’Higgins": [
    "Rancagua",
    "Codegua",
    "Coinco",
    "Coltauco",
    "Doñihue",
    "Graneros",
    "Las Cabras",
    "Machalí",
    "Malloa",
    "Mostazal",
    "Olivar",
    "Peumo",
    "Pichidegua",
    "Quinta de Tilcoco",
    "Rengo",
    "Requínoa",
    "San Vicente",
    "Pichilemu",
    "La Estrella",
    "Litueche",
    "Marchihue",
    "Navidad",
    "Paredones",
    "San Fernando",
    "Chépica",
    "Chimbarongo",
    "Lolol",
    "Nancagua",
    "Palmilla",
    "Peralillo",
    "Placilla",
    "Pumanque",
    "Santa Cruz",
  ],
  "Región del Maule": [
    "Talca",
    "Constitución",
    "Curepto",
    "Empedrado",
    "Maule",
    "Pelarco",
    "Pencahue",
    "Río Claro",
    "San Clemente",
    "San Rafael",
    "Cauquenes",
    "Chanco",
    "Pelluhue",
    "Curicó",
    "Hualañé",
    "Licantén",
    "Molina",
    "Rauco",
    "Romeral",
    "Sagrada Familia",
    "Teno",
    "Vichuquén",
    "Linares",
    "Colbún",
    "Longaví",
    "Parral",
    "Retiro",
    "San Javier",
    "Villa Alegre",
    "Yerbas Buenas",
  ],
  "Región de Ñuble": [
    "Cobquecura",
    "Coelemu",
    "Ninhue",
    "Portezuelo",
    "Quirihue",
    "Ránquil",
    "Treguaco",
    "Bulnes",
    "Chillán Viejo",
    "Chillán",
    "El Carmen",
    "Pemuco",
    "Pinto",
    "Quillón",
    "San Ignacio",
    "Yungay",
    "Coihueco",
    "Ñiquén",
    "San Carlos",
    "San Fabián",
    "San Nicolás",
  ],
  "Región del Biobío": [
    "Concepción",
    "Coronel",
    "Chiguayante",
    "Florida",
    "Hualqui",
    "Lota",
    "Penco",
    "San Pedro de la Paz",
    "Santa Juana",
    "Talcahuano",
    "Tomé",
    "Hualpén",
    "Lebu",
    "Arauco",
    "Cañete",
    "Contulmo",
    "Curanilahue",
    "Los Álamos",
    "Tirúa",
    "Los Ángeles",
    "Antuco",
    "Cabrero",
    "Laja",
    "Mulchén",
    "Nacimiento",
    "Negrete",
    "Quilaco",
    "Quilleco",
    "San Rosendo",
    "Santa Bárbara",
    "Tucapel",
    "Yumbel",
    "Alto Biobío",
  ],
  "Región de la Araucanía": [
    "Temuco",
    "Carahue",
    "Cunco",
    "Curarrehue",
    "Freire",
    "Galvarino",
    "Gorbea",
    "Lautaro",
    "Loncoche",
    "Melipeuco",
    "Nueva Imperial",
    "Padre las Casas",
    "Perquenco",
    "Pitrufquén",
    "Pucón",
    "Saavedra",
    "Teodoro Schmidt",
    "Toltén",
    "Vilcún",
    "Villarrica",
    "Cholchol",
    "Angol",
    "Collipulli",
    "Curacautín",
    "Ercilla",
    "Lonquimay",
    "Los Sauces",
    "Lumaco",
    "Purén",
    "Renaico",
    "Traiguén",
    "Victoria",
  ],
  "Región de Los Ríos": [
    "Valdivia",
    "Corral",
    "Lanco",
    "Los Lagos",
    "Máfil",
    "Mariquina",
    "Paillaco",
    "Panguipulli",
    "La Unión",
    "Futrono",
    "Lago Ranco",
    "Río Bueno",
  ],
  "Región de Los Lagos": [
    "Puerto Montt",
    "Calbuco",
    "Cochamó",
    "Fresia",
    "Frutillar",
    "Los Muermos",
    "Llanquihue",
    "Maullín",
    "Puerto Varas",
    "Castro",
    "Ancud",
    "Chonchi",
    "Curaco de Vélez",
    "Dalcahue",
    "Puqueldón",
    "Queilén",
    "Quellón",
    "Quemchi",
    "Quinchao",
    "Osorno",
    "Puerto Octay",
    "Purranque",
    "Puyehue",
    "Río Negro",
    "San Juan de la Costa",
    "San Pablo",
    "Chaitén",
    "Futaleufú",
    "Hualaihué",
    "Palena",
  ],
  "Región Aisén del Gral. Carlos Ibáñez del Campo": [
    "Coihaique",
    "Lago Verde",
    "Aisén",
    "Cisnes",
    "Guaitecas",
    "Cochrane",
    "O’Higgins",
    "Tortel",
    "Chile Chico",
    "Río Ibáñez",
  ],
  "Región de Magallanes y de la Antártica Chilena": [
    "Punta Arenas",
    "Laguna Blanca",
    "Río Verde",
    "San Gregorio",
    "Cabo de Hornos (Ex Navarino)",
    "Antártica",
    "Porvenir",
    "Primavera",
    "Timaukel",
    "Natales",
    "Torres del Paine",
  ],
  "Región Metropolitana de Santiago": [
    "Cerrillos",
    "Cerro Navia",
    "Conchalí",
    "El Bosque",
    "Estación Central",
    "Huechuraba",
    "Independencia",
    "La Cisterna",
    "La Florida",
    "La Granja",
    "La Pintana",
    "La Reina",
    "Las Condes",
    "Lo Barnechea",
    "Lo Espejo",
    "Lo Prado",
    "Macul",
    "Maipú",
    "Ñuñoa",
    "Pedro Aguirre Cerda",
    "Peñalolén",
    "Providencia",
    "Pudahuel",
    "Quilicura",
    "Quinta Normal",
    "Recoleta",
    "Renca",
    "Santiago",
    "San Joaquín",
    "San Miguel",
    "San Ramón",
    "Vitacura",
    "Puente Alto",
    "Pirque",
    "San José de Maipo",
    "Colina",
    "Lampa",
    "Tiltil",
    "San Bernardo",
    "Buin",
    "Calera de Tango",
    "Paine",
    "Melipilla",
    "Alhué",
    "Curacaví",
    "María Pinto",
    "San Pedro",
    "Talagante",
    "El Monte",
    "Isla de Maipo",
    "Padre Hurtado",
    "Peñaflor",
  ],
};
